#Validaciones de las clases bajo el directorio Entity
Salita\TurnoBundle\Entity\Turno:
    properties:
        especialidad:
            - NotNull: ~
        motivo:
            - NotBlank:
                message: 'turnobundle.turno.motivo.notBlank'