salita_usuario:
    resource: "@SalitaUsuarioBundle/Resources/config/routing.yml"
    prefix:   /

salita_turno:
    resource: "@SalitaTurnoBundle/Resources/config/routing.yml"
    prefix:   /

salita_plan:
    resource: "@SalitaPlanBundle/Resources/config/routing.yml"
    prefix:   /

salita_paciente:
    resource: "@SalitaPacienteBundle/Resources/config/routing.yml"
    prefix:   /

salita_otros:
    resource: "@SalitaOtrosBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   / 

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /