INSERT INTO localidad (nombre, idPartido) VALUES ('Abasto',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Barrio El Carmen',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Barrio Gambier',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Barrio Las Malvinas',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Barrio Las Quintas',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Ángel Etcheverry',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Arana',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Arturo Seguí',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('City Bell',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('El Retiro',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Joaquín Gorina',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('José Hernández',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('José Melchor Romero',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('La Cumbre',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('La Plata',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Lisandro Olmos',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Los Hornos',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Manuel B. Gonnet',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Ringuelet',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Altos de San Lorenzo',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Tolosa',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Elisa',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Elvira',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Garibaldi',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Montoro',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Parque Sicardi',1);
INSERT INTO localidad (nombre, idPartido) VALUES ('Ensenada',2);
INSERT INTO localidad (nombre, idPartido) VALUES ('Punta Lara',2);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Catella',2);
INSERT INTO localidad (nombre, idPartido) VALUES ('Dique Nº 1',2);
INSERT INTO localidad (nombre, idPartido) VALUES ('Isla Santiago',2);
INSERT INTO localidad (nombre, idPartido) VALUES ('Berisso',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Porteña',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Progreso',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa San Carlos',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Dolores',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Independencia',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Corbalan',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Argüello',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Zula',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Barrio Banco Provincia',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Nueva',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Barrio Universitario',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Los Talas',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Palo Blanco',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa Banco Constructor',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Los Catorce',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa España',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('La Balandra',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Juan B.Justo',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Barrio Obrero',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Barrio Santa Teresita',3);
INSERT INTO localidad (nombre, idPartido) VALUES ('Bernal',4);
INSERT INTO localidad (nombre, idPartido) VALUES ('Don Bosco',4);
INSERT INTO localidad (nombre, idPartido) VALUES ('Ezpeleta',4);
INSERT INTO localidad (nombre, idPartido) VALUES ('Quilmes',4);
INSERT INTO localidad (nombre, idPartido) VALUES ('San Francisco Solano',4);
INSERT INTO localidad (nombre, idPartido) VALUES ('Villa La Florida',4);
INSERT INTO localidad (nombre, idPartido) VALUES ('Magdalena',5);
INSERT INTO localidad (nombre, idPartido) VALUES ('General Mansilla',5);
INSERT INTO localidad (nombre, idPartido) VALUES ('Atalaya',5);
INSERT INTO localidad (nombre, idPartido) VALUES ('Vieytes',5);
INSERT INTO localidad (nombre, idPartido) VALUES ('Roberto J. Payró',5);
INSERT INTO localidad (nombre, idPartido) VALUES ('Los Naranjos',5);
INSERT INTO localidad (nombre, idPartido) VALUES ('Brandsen',6);
INSERT INTO localidad (nombre, idPartido) VALUES ('Jeppener',6);
INSERT INTO localidad (nombre, idPartido) VALUES ('Altamirano',6);
INSERT INTO localidad (nombre, idPartido) VALUES ('Gómez',6);
INSERT INTO localidad (nombre, idPartido) VALUES ('Oliden',6);
INSERT INTO localidad (nombre, idPartido) VALUES ('Samborombón',6);

